### PR TITLE
Revert "[TPC-H] Refactor query 9 to avoid recursion error in dask-expr"

### PR DESCRIPTION
**Pull request by phofl**
Reverts coiled/benchmarks#1277

can not reproduce locally

### CODE REVIEW

**Comment by milesgranger** [comment]
> can not reproduce locally

Weird, I can still produce it with the latest release (0.3.5) on this PR (dask 2024.1.1)

**Comment by phofl** [comment]
Using lambdas is inherently bad in systems that can be optimised, so we should start warning users about this at some point when we have column expressions. There is not much point in benchmarking this and shooting ourselves in the foot on purpose while doing so. You are shuffling and reading the whole dataset which is just incredibly slow, which explains the timeouts

I was doing something dumb, which hid the error from me, sorry.

**Comment by phofl** [comment]
@milesgranger Could you push this over the finish line? it looks like the query is schematically off

**Comment by milesgranger** [comment]
@phofl ready now, failures are unrelated.

>FAILED tests/tpch/test_dask.py::test_query_10 - RuntimeError: shuffle_barrier failed during shuffle 9a0b09c0c0f40cd95e7fa7560513bb54
ERROR tests/tpch/test_dask.py::test_query_11 - asyncio.exceptions.TimeoutError: 1/16 nanny worker(s) did not shut down within 120s

**Review by hendrikmakait — APPROVED** [review]
Thanks!

**Pull request merged**
