### PR TITLE
Use `da.random.default_rng` API for random array creation

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by jrbourbeau** [comment]
@hendrikmakait let's see if this helps with https://github.com/coiled/benchmarks/issues/789 (though this is definitely just a shot in the dark)

**Comment by jrbourbeau** [comment]
Alright, I've run CI here four times and haven't run into https://github.com/coiled/benchmarks/issues/789 yet. @hendrikmakait let me know what you think

**Review by hendrikmakait — APPROVED** [review]
Thanks, @jrbourbeau! I'd like to know why this happened, but since it doesn't seem to pop up in any production setting, I'm okay with using this workaround.

**Comment by jrbourbeau** [comment]
Yeah, I'd like a better understanding of what's going on here too. 

cc @rjzamora @erayaslan who have been pushing on the `Generator` API for random arrays in `dask.array`. We recently started seeing error like

```python
_________________________ test_rechunk_in_memory[p2p] __________________________
[gw0] linux -- Python 3.9.16 /usr/share/miniconda3/envs/test/bin/python

small_client = <Client: 'tls://10.0.13.228:8786' processes=10 threads=20, memory=71.68 GiB>
configure_rechunking = None

    @run_up_to_nthreads("small_cluster", 50, reason="fixed dataset")
    def test_rechunk_in_memory(small_client, configure_rechunking):
        x = da.random.random((50000, 50000))
>       x.rechunk((50000, 20)).rechunk((20, 50000)).sum().compute()

tests/benchmarks/test_array.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/dask/base.py:314: in compute
    (result,) = compute(self, traverse=False, **kwargs)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/dask/base.py:599: in compute
    results = schedule(dsk, keys, **kwargs)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/client.py:3213: in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/client.py:2348: in gather
    return self.sync(
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/utils.py:349: in sync
    return sync(
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/utils.py:416: in sync
    raise exc.with_traceback(tb)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/utils.py:389: in f
    result = yield future
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/tornado/gen.py:769: in run
    value = future.result()
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/client.py:2211: in _gather
    raise exception.with_traceback(traceback)
/opt/coiled/env/lib/python3.9/site-packages/dask/array/random.py:816: in _apply_random
    ???
mtrand.pyx:185: in numpy.random.mtrand.RandomState.__init__
    ???
_mt19937.pyx:166: in numpy.random._mt19937.MT19937._legacy_seeding
    ???
_mt19937.pyx:189: in numpy.random._mt19937.MT19937._legacy_seeding
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   RuntimeError: Identity cache already includes the item.

/opt/coiled/env/lib/python3.9/site-packages/numpy/core/_methods.py:57: RuntimeError
```

here where we were using `da.random.random(...)`. When switching to the new `da.random.default_rng` API, these errors  go away. Any idea what might be going on? This seems like a regression in the non-`Generator` API

**Comment by erayaslan** [comment]
Well, this is surprising.
- I could not reproduce the error, i.e. `test_rechunk_in_memory` works with or without `dask.distributed`. Obviously, I do not have access to a coiled environment and I could not see what is different about it to make the test fail.
- @rjzamora Can this be `dispatch` or `_make_api` related? Should be easy to test if you can reproduce the error (I am assuming you have access to a coiled env)

**Comment by dchudz** [comment]
> Obviously, I do not have access to a coiled environment and I could not
see what is different about it to make the test fail.

If you're interested in access to a Coiled environment for testing anything
like this, I can make it happen. (No commitment, fine if I give you the
environment and you don't have a chance to use it.)

**Comment by erayaslan** [comment]
> If you're interested in access to a Coiled environment for testing anything like this, I can make it happen

Thank you @dchudz . I would definitely like to have access to a Coiled environment. We should try to figure out why it was failing

**Comment by erayaslan** [comment]
@mrocklin  thank you. logged in to cloud.coiled.io with my github credentials.

**Pull request merged**
