### PR TITLE
[DO NOT MERGE] see if this fixes the regression

### PR DESCRIPTION
**Pull request by j-bennet**
See if this fixes the regression in `make_timeseries` https://github.com/coiled/benchmarks/issues/910.

Xref https://github.com/dask/dask/pull/10428.

### CODE REVIEW

**Comment by j-bennet** [comment]
Looks like this didn't help. :(

image

Might be best to revert https://github.com/dask/dask/pull/10392, and have another version that doesn't touch `make_timeseries` at all.

**Comment by phofl** [comment]
Hm that's unfortunate. Maybe try dask pyspy?

**Comment by j-bennet** [comment]
> Hm that's unfortunate. Maybe try dask pyspy?

I have, but with the multiple threads, the picture is still pretty complicated. I'll try simplifying it + limiting threads.

**Comment by j-bennet** [comment]
Yes! It did it.

image

**Pull request closed without merging**
