### PR TITLE
Fix tpch related failures

### PR DESCRIPTION
**Pull request by phofl**

### CODE REVIEW

**Comment by mrocklin** [comment]
What was the failure?

**Comment by hendrikmakait** [comment]
@mrocklin: https://github.com/coiled/benchmarks/issues/1140#issuecomment-1778858242

**Comment by mrocklin** [comment]
@phofl how hard would it be to improve your fix in the dask-expr testing branch?

**Comment by mrocklin** [comment]
Or maybe https://github.com/dask/dask/pull/10590 resolves this (the string is easy to tokenize)

**Comment by phofl** [comment]
Yeah string will work, we can revert this then, but CI is broken which makes triage hard

**Comment by mrocklin** [comment]
Do what you need to do.  If someone on the Dask team can also review https://github.com/dask/dask/pull/10590 or https://github.com/dask/dask/pull/10599 in short order i'd appreciate it

**Review by hendrikmakait — APPROVED** [review]

**Pull request merged**
