### PR TITLE
Add timeout to test_read_spark_generated_data

### PR DESCRIPTION
**Pull request by crusaderky**
- XREF #998

### CODE REVIEW

**Comment by crusaderky** [comment]
It's not stuck; it's just exceptionally slow. dataframe-groupby-first-chunk takes 30+ minutes per task.

**Comment by crusaderky** [comment]
It completes now. Technically.
```
11147.00s call  tests/benchmarks/test_parquet.py::test_read_spark_generated_data
627.72s call     tests/benchmarks/test_join.py::test_join_big[1-tasks]
417.69s call     tests/benchmarks/test_spill.py::test_dot_product_spill[compressible]
```

**Comment by crusaderky** [comment]
PR works as intended; please merge

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @crusaderky

**Pull request merged**
