### PR TITLE
Add session token for duckdb AWS use

### LINKED ISSUE #1068: TPCH - DuckDB Failures
I'm getting segfaults when running DuckDB locally.  

When I run as-is I get the following:

```
E       duckdb.duckdb.HTTPException: HTTP Error: HTTP GET error on '/?encoding-type=url&list-type=2&prefix=tpch_scale_100%2Flineitem%2F' (HTTP 403)
```

This is after going through a clean install as outlined in the README, followed by the following:

```
py.test tests/benchmarks/tpch/test_duckdb.py::test_query_1 --tpch-non-dask
```

@milesgranger I'm guessing that you're probably the best positioned to help here

### PR DESCRIPTION
**Pull request by milesgranger**
Fix #1068

After coiled https://github.com/coiled/platform/pull/3396 switch in credential handling, and similar to #1076 this updates duckdb failing by adding a missing session token.

### CODE REVIEW

**Comment by phofl** [comment]
The extension https://duckdb.org/docs/extensions/aws should handle the variables automatically with the newest duckdb release (0.9.x). At least that was the promise when I wrote my blog post but that was before 0.9.x was out

**Comment by milesgranger** [comment]
I tried that.

`CALL load_aws_credentials()` but it does not work, and is experimental anyway so I didn't chase it much further beyond that. (tried setting and not setting region as well in this exploration with no additional benefit)

**Comment by phofl** [comment]
Ok that's a pity, you can ignore my comment then

**Comment by crusaderky** [comment]
query_1 fails in CI neither before nor after this PR, even if the coiled version is 1.1.0.
Not sure what's the expected change?

**Review by mrocklin — APPROVED** [review]
Things used to fail for me before and now they run.  I'm +1 on this.

**Comment by mrocklin** [comment]
Although I don't know about CI failures.  Were things already failing on main?

**Comment by milesgranger** [comment]
@mrocklin, that's being looked into now by @phofl 
https://github.com/coiled/benchmarks/actions/runs/6532939100/job/17737096347#step:10:750

**Pull request merged**
